#!/bin/zsh
# -*- mode: sh-mode -*-

# Very simple/rudimentary test for this

wilt_result=$(./wilt ./wilt)

# assert bounded: msg, arg, min, max
ab () {
    if [[ $2 > $3 && $2 < $4 ]]; then
        echo -e "Assertion pass on: '$1' \n  (expected: t === $3 < $2 < $4)"
    else
        echo -e "Assertion fail on: '$1' \n  (expected: t === $3 < $2 < $4)"
        exit 1
    fi
}

ab "It produces some result" $(./wilt ./wilt) 1 3
ab "It produces some result with flags" $(./wilt -vsmart=t ./wilt) 1 3
